[workspace]
resolver = "2"
members = [
   "roland_test_runner",
   "rolandc",
   "rolandc_cli",
   "rolandc_web",
   "rolandc_lsp",
]

[profile.release]
panic = "abort"

[profile.dhat]
inherits = "release"
debug = true
