[workspace]
resolver = "2"
members = [
   "roland_test_runner",
   "rolandc",
   "rolandc_cli",
   "rolandc_web",
   "rolandc_lsp",
]

[profile.release]
panic = "abort"
# Overriden in CI to false
incremental = true

[profile.dhat]
inherits = "release"
debug = true
incremental = false
