[workspace]

members = [
   "roland_test_runner",
   "rolandc",
   "rolandc_cli",
   "rolandc_wasm",
   "rolandc_lsp",
]

[profile.release]
panic = "abort"

[profile.dhat]
inherits = "release"
debug = true
