[package]
name = "rolandc"
version = "0.1.0"
authors = ["Richard McCormack <brick@brick.codes>"]
edition = "2021"

[dependencies]
unicode-ident = "1"
arrayvec = "0.7"
indexmap = "1"
wat = "1"
include_dir = "0.7"
