[package]
name = "rolandc"
version = "0.1.0"
authors = ["Richard McCormack <brick@brick.codes>"]
edition = "2021"

[dependencies]
arrayvec = "0.7"
unicode-ident = "1"
indexmap = "2"
include_dir = "0.7"
wasm-encoder = "0.227"
slotmap = "1"
bitvec = "1"